import { ICard } from '../../domain/types';
import { CARD_CONDITIONS } from '../../domain/constants';
import { TCG_TYPES } from '@/lib/types/tcg.types';

export const MOCK_CARDS: ICard[] = [
  {
    id: 'pkmn-001',
    name: 'Charizard ex',
    setName: 'Obsidian Flames',
    setCode: 'OBF',
    number: '125',
    rarity: 'Special Art Rare',
    imageUrl: 'https://images.pokemontcg.io/sv3/125_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-001-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 3,
        buyPrice: 45.0,
        sellPrice: 65.0,
      },
      {
        id: 'pkmn-001-lp',
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        stock: 1,
        buyPrice: 35.0,
        sellPrice: 50.0,
      },
    ],
  },
  {
    id: 'pkmn-002',
    name: 'Pikachu VMAX',
    setName: 'Vivid Voltage',
    setCode: 'VIV',
    number: '044',
    rarity: 'Ultra Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh4/44_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-002-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 5,
        buyPrice: 20.0,
        sellPrice: 30.0,
      },
    ],
  },
  {
    id: 'pkmn-003',
    name: 'Mewtwo V',
    setName: 'Pokémon GO',
    setCode: 'PGO',
    number: '030',
    rarity: 'Rare Holo V',
    imageUrl: 'https://images.pokemontcg.io/pgo/30_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-003-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 8.0,
        sellPrice: 12.0,
      },
      {
        id: 'pkmn-003-mp',
        condition: CARD_CONDITIONS.MODERATELY_PLAYED,
        stock: 1,
        buyPrice: 5.0,
        sellPrice: 8.0,
      },
    ],
  },
  {
    id: 'pkmn-004',
    name: 'Umbreon VMAX',
    setName: 'Evolving Skies',
    setCode: 'EVS',
    number: '095',
    rarity: 'Secret Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh7/95_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-004-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 1,
        buyPrice: 180.0,
        sellPrice: 250.0,
      },
    ],
  },
  {
    id: 'pkmn-005',
    name: 'Gardevoir ex',
    setName: 'Scarlet & Violet',
    setCode: 'SVI',
    number: '086',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/sv1/86_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-005-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 4,
        buyPrice: 6.0,
        sellPrice: 10.0,
      },
      {
        id: 'pkmn-005-hp',
        condition: CARD_CONDITIONS.HEAVILY_PLAYED,
        stock: 2,
        buyPrice: 3.0,
        sellPrice: 5.0,
      },
    ],
  },
  {
    id: 'pkmn-006',
    name: 'Lugia V',
    setName: 'Silver Tempest',
    setCode: 'SIT',
    number: '138',
    rarity: 'Ultra Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh12pt5/138_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-006-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 12.0,
        sellPrice: 18.0,
      },
    ],
  },
  {
    id: 'mtg-001',
    name: 'Lightning Bolt',
    setName: 'Fourth Edition',
    setCode: '4ED',
    number: '208',
    rarity: 'Common',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-001-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 10,
        buyPrice: 2.0,
        sellPrice: 3.5,
      },
      {
        id: 'mtg-001-lp',
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        stock: 5,
        buyPrice: 1.5,
        sellPrice: 2.5,
      },
    ],
  },
  {
    id: 'mtg-002',
    name: 'Ragavan, Nimble Pilferer',
    setName: 'Modern Horizons 2',
    setCode: 'MH2',
    number: '138',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-002-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 55.0,
        sellPrice: 75.0,
      },
    ],
  },
  {
    id: 'mtg-003',
    name: 'Sheoldred, the Apocalypse',
    setName: 'Dominaria United',
    setCode: 'DMU',
    number: '107',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-003-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 1,
        buyPrice: 70.0,
        sellPrice: 95.0,
      },
      {
        id: 'mtg-003-dmg',
        condition: CARD_CONDITIONS.DAMAGED,
        stock: 1,
        buyPrice: 30.0,
        sellPrice: 45.0,
      },
    ],
  },
  {
    id: 'mtg-004',
    name: 'Counterspell',
    setName: 'Modern Horizons 2',
    setCode: 'MH2',
    number: '267',
    rarity: 'Uncommon',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-004-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 8,
        buyPrice: 1.0,
        sellPrice: 2.0,
      },
    ],
  },
  {
    id: 'mtg-005',
    name: 'The One Ring',
    setName: 'Lord of the Rings',
    setCode: 'LTR',
    number: '246',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-005-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 1,
        buyPrice: 40.0,
        sellPrice: 60.0,
      },
      {
        id: 'mtg-005-lp',
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        stock: 2,
        buyPrice: 30.0,
        sellPrice: 45.0,
      },
    ],
  },
  {
    id: 'mtg-006',
    name: 'Fatal Push',
    setName: 'Aether Revolt',
    setCode: 'AER',
    number: '057',
    rarity: 'Uncommon',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-006-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 6,
        buyPrice: 3.0,
        sellPrice: 5.0,
      },
    ],
  },
];
