import { ICard } from '../../domain/types';
import { CARD_CONDITIONS } from '../../domain/constants';
import { TCG_TYPES } from '@/lib/types/tcg.types';

export const MOCK_CARDS: ICard[] = [
  {
    id: 'pkmn-001',
    name: 'Charizard ex',
    setName: 'Obsidian Flames',
    setCode: 'OBF',
    number: '125',
    rarity: 'Special Art Rare',
    imageUrl: 'https://images.pokemontcg.io/sv3/125_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-001-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 3,
        buyPrice: 45.0,
        sellPrice: 65.0,
      },
      {
        id: 'pkmn-001-lp',
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        stock: 1,
        buyPrice: 35.0,
        sellPrice: 50.0,
      },
    ],
  },
  {
    id: 'pkmn-002',
    name: 'Pikachu VMAX',
    setName: 'Vivid Voltage',
    setCode: 'VIV',
    number: '044',
    rarity: 'Ultra Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh4/44_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-002-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 5,
        buyPrice: 20.0,
        sellPrice: 30.0,
      },
    ],
  },
  {
    id: 'pkmn-003',
    name: 'Mewtwo V',
    setName: 'Pokémon GO',
    setCode: 'PGO',
    number: '030',
    rarity: 'Rare Holo V',
    imageUrl: 'https://images.pokemontcg.io/pgo/30_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-003-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 8.0,
        sellPrice: 12.0,
      },
      {
        id: 'pkmn-003-mp',
        condition: CARD_CONDITIONS.MODERATELY_PLAYED,
        stock: 1,
        buyPrice: 5.0,
        sellPrice: 8.0,
      },
    ],
  },
  {
    id: 'pkmn-004',
    name: 'Umbreon VMAX',
    setName: 'Evolving Skies',
    setCode: 'EVS',
    number: '095',
    rarity: 'Secret Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh7/95_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-004-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 1,
        buyPrice: 180.0,
        sellPrice: 250.0,
      },
    ],
  },
  {
    id: 'pkmn-005',
    name: 'Gardevoir ex',
    setName: 'Scarlet & Violet',
    setCode: 'SVI',
    number: '086',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/sv1/86_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-005-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 4,
        buyPrice: 6.0,
        sellPrice: 10.0,
      },
      {
        id: 'pkmn-005-hp',
        condition: CARD_CONDITIONS.HEAVILY_PLAYED,
        stock: 2,
        buyPrice: 3.0,
        sellPrice: 5.0,
      },
    ],
  },
  {
    id: 'pkmn-006',
    name: 'Lugia V',
    setName: 'Silver Tempest',
    setCode: 'SIT',
    number: '138',
    rarity: 'Ultra Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh12pt5/138_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-006-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 12.0,
        sellPrice: 18.0,
      },
    ],
  },
  {
    id: 'pkmn-007',
    name: 'Pokémon Catcher',
    setName: 'Emerging Powers',
    setCode: 'EPO',
    number: '095',
    rarity: 'Uncommon',
    imageUrl: 'https://images.pokemontcg.io/bw2/95_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-007-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 12,
        buyPrice: 1.5,
        sellPrice: 3.0,
      },
      {
        id: 'pkmn-007-lp',
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        stock: 4,
        buyPrice: 1.0,
        sellPrice: 2.0,
      },
    ],
  },
  {
    id: 'pkmn-008',
    name: 'Rayquaza VMAX',
    setName: 'Evolving Skies',
    setCode: 'EVS',
    number: '218',
    rarity: 'Secret Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh7/218_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-008-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 1,
        buyPrice: 85.0,
        sellPrice: 120.0,
      },
    ],
  },
  {
    id: 'pkmn-009',
    name: 'Mew VMAX',
    setName: 'Fusion Strike',
    setCode: 'FST',
    number: '269',
    rarity: 'Secret Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh8/269_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-009-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 30.0,
        sellPrice: 45.0,
      },
      {
        id: 'pkmn-009-mp',
        condition: CARD_CONDITIONS.MODERATELY_PLAYED,
        stock: 1,
        buyPrice: 18.0,
        sellPrice: 28.0,
      },
    ],
  },
  {
    id: 'pkmn-010',
    name: 'Arceus VSTAR',
    setName: 'Brilliant Stars',
    setCode: 'BRS',
    number: '123',
    rarity: 'Ultra Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh9/123_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-010-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 3,
        buyPrice: 15.0,
        sellPrice: 22.0,
      },
    ],
  },
  {
    id: 'pkmn-011',
    name: 'Giratina VSTAR',
    setName: 'Lost Origin',
    setCode: 'LOR',
    number: '131',
    rarity: 'Ultra Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh11/131_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-011-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 10.0,
        sellPrice: 16.0,
      },
      {
        id: 'pkmn-011-lp',
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        stock: 3,
        buyPrice: 7.0,
        sellPrice: 12.0,
      },
    ],
  },
  {
    id: 'pkmn-012',
    name: 'Palkia VSTAR',
    setName: 'Astral Radiance',
    setCode: 'ASR',
    number: '040',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh10/40_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-012-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 4,
        buyPrice: 8.0,
        sellPrice: 13.0,
      },
    ],
  },
  {
    id: 'pkmn-013',
    name: 'Eevee',
    setName: 'Scarlet & Violet',
    setCode: 'SVI',
    number: '130',
    rarity: 'Common',
    imageUrl: 'https://images.pokemontcg.io/sv1/130_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-013-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 20,
        buyPrice: 0.5,
        sellPrice: 1.0,
      },
    ],
  },
  {
    id: 'pkmn-014',
    name: 'Miraidon ex',
    setName: 'Scarlet & Violet',
    setCode: 'SVI',
    number: '081',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/sv1/81_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-014-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 3,
        buyPrice: 5.0,
        sellPrice: 9.0,
      },
      {
        id: 'pkmn-014-hp',
        condition: CARD_CONDITIONS.HEAVILY_PLAYED,
        stock: 1,
        buyPrice: 2.0,
        sellPrice: 4.0,
      },
    ],
  },
  {
    id: 'pkmn-015',
    name: 'Koraidon ex',
    setName: 'Scarlet & Violet',
    setCode: 'SVI',
    number: '125',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/sv1/125_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-015-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 4.0,
        sellPrice: 7.0,
      },
    ],
  },
  {
    id: 'pkmn-016',
    name: 'Ting-Lu ex',
    setName: 'Paldea Evolved',
    setCode: 'PAL',
    number: '127',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/sv2/127_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-016-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 5,
        buyPrice: 3.0,
        sellPrice: 5.5,
      },
      {
        id: 'pkmn-016-dmg',
        condition: CARD_CONDITIONS.DAMAGED,
        stock: 1,
        buyPrice: 1.0,
        sellPrice: 2.0,
      },
    ],
  },
  {
    id: 'pkmn-017',
    name: 'Blastoise ex',
    setName: 'Paldea Evolved',
    setCode: 'PAL',
    number: '186',
    rarity: 'Special Art Rare',
    imageUrl: 'https://images.pokemontcg.io/sv2/186_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-017-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 1,
        buyPrice: 22.0,
        sellPrice: 35.0,
      },
    ],
  },
  {
    id: 'pkmn-018',
    name: 'Chien-Pao ex',
    setName: 'Paldea Evolved',
    setCode: 'PAL',
    number: '061',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/sv2/61_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-018-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 6,
        buyPrice: 4.0,
        sellPrice: 7.0,
      },
      {
        id: 'pkmn-018-lp',
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        stock: 2,
        buyPrice: 2.5,
        sellPrice: 5.0,
      },
    ],
  },
  {
    id: 'pkmn-019',
    name: 'Roaring Moon ex',
    setName: 'Paldea Evolved',
    setCode: 'PAL',
    number: '109',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/sv2/109_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-019-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 3,
        buyPrice: 5.0,
        sellPrice: 8.0,
      },
    ],
  },
  {
    id: 'pkmn-020',
    name: 'Gengar ex',
    setName: 'Obsidian Flames',
    setCode: 'OBF',
    number: '104',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/sv3/104_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-020-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 4,
        buyPrice: 3.5,
        sellPrice: 6.0,
      },
      {
        id: 'pkmn-020-mp',
        condition: CARD_CONDITIONS.MODERATELY_PLAYED,
        stock: 2,
        buyPrice: 2.0,
        sellPrice: 4.0,
      },
    ],
  },
  {
    id: 'pkmn-021',
    name: 'Tyranitar ex',
    setName: 'Obsidian Flames',
    setCode: 'OBF',
    number: '134',
    rarity: 'Special Art Rare',
    imageUrl: 'https://images.pokemontcg.io/sv3/134_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-021-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 1,
        buyPrice: 15.0,
        sellPrice: 24.0,
      },
    ],
  },
  {
    id: 'pkmn-022',
    name: 'Dragonite V',
    setName: 'Silver Tempest',
    setCode: 'SIT',
    number: '049',
    rarity: 'Rare Holo V',
    imageUrl: 'https://images.pokemontcg.io/swsh12pt5/49_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-022-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 5,
        buyPrice: 2.0,
        sellPrice: 4.0,
      },
      {
        id: 'pkmn-022-hp',
        condition: CARD_CONDITIONS.HEAVILY_PLAYED,
        stock: 3,
        buyPrice: 0.75,
        sellPrice: 1.5,
      },
    ],
  },
  {
    id: 'pkmn-023',
    name: 'Sylveon VMAX',
    setName: 'Evolving Skies',
    setCode: 'EVS',
    number: '212',
    rarity: 'Secret Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh7/212_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-023-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 1,
        buyPrice: 40.0,
        sellPrice: 60.0,
      },
    ],
  },
  {
    id: 'pkmn-024',
    name: 'Espeon VMAX',
    setName: 'Evolving Skies',
    setCode: 'EVS',
    number: '065',
    rarity: 'Ultra Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh7/65_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-024-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 12.0,
        sellPrice: 20.0,
      },
      {
        id: 'pkmn-024-lp',
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        stock: 1,
        buyPrice: 8.0,
        sellPrice: 14.0,
      },
      {
        id: 'pkmn-024-dmg',
        condition: CARD_CONDITIONS.DAMAGED,
        stock: 1,
        buyPrice: 3.0,
        sellPrice: 6.0,
      },
    ],
  },
  {
    id: 'pkmn-025',
    name: 'Leafeon VSTAR',
    setName: 'Crown Zenith',
    setCode: 'CRZ',
    number: '014',
    rarity: 'Ultra Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh12pt5gg/14_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-025-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 3,
        buyPrice: 4.0,
        sellPrice: 7.0,
      },
    ],
  },
  {
    id: 'pkmn-026',
    name: 'Glaceon VSTAR',
    setName: 'Crown Zenith',
    setCode: 'CRZ',
    number: '027',
    rarity: 'Ultra Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh12pt5gg/27_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    variants: [
      {
        id: 'pkmn-026-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 5.0,
        sellPrice: 9.0,
      },
      {
        id: 'pkmn-026-mp',
        condition: CARD_CONDITIONS.MODERATELY_PLAYED,
        stock: 1,
        buyPrice: 3.0,
        sellPrice: 5.5,
      },
    ],
  },
  {
    id: 'mtg-001',
    name: 'Lightning Bolt',
    setName: 'Fourth Edition',
    setCode: '4ED',
    number: '208',
    rarity: 'Common',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-001-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 10,
        buyPrice: 2.0,
        sellPrice: 3.5,
      },
      {
        id: 'mtg-001-lp',
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        stock: 5,
        buyPrice: 1.5,
        sellPrice: 2.5,
      },
    ],
  },
  {
    id: 'mtg-002',
    name: 'Ragavan, Nimble Pilferer',
    setName: 'Modern Horizons 2',
    setCode: 'MH2',
    number: '138',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-002-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 55.0,
        sellPrice: 75.0,
      },
    ],
  },
  {
    id: 'mtg-003',
    name: 'Sheoldred, the Apocalypse',
    setName: 'Dominaria United',
    setCode: 'DMU',
    number: '107',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-003-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 1,
        buyPrice: 70.0,
        sellPrice: 95.0,
      },
      {
        id: 'mtg-003-dmg',
        condition: CARD_CONDITIONS.DAMAGED,
        stock: 1,
        buyPrice: 30.0,
        sellPrice: 45.0,
      },
    ],
  },
  {
    id: 'mtg-004',
    name: 'Counterspell',
    setName: 'Modern Horizons 2',
    setCode: 'MH2',
    number: '267',
    rarity: 'Uncommon',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-004-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 8,
        buyPrice: 1.0,
        sellPrice: 2.0,
      },
    ],
  },
  {
    id: 'mtg-005',
    name: 'The One Ring',
    setName: 'Lord of the Rings',
    setCode: 'LTR',
    number: '246',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-005-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 1,
        buyPrice: 40.0,
        sellPrice: 60.0,
      },
      {
        id: 'mtg-005-lp',
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        stock: 2,
        buyPrice: 30.0,
        sellPrice: 45.0,
      },
    ],
  },
  {
    id: 'mtg-006',
    name: 'Fatal Push',
    setName: 'Aether Revolt',
    setCode: 'AER',
    number: '057',
    rarity: 'Uncommon',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-006-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 6,
        buyPrice: 3.0,
        sellPrice: 5.0,
      },
    ],
  },
  {
    id: 'mtg-007',
    name: 'Wrenn and Six',
    setName: 'Modern Horizons',
    setCode: 'MH1',
    number: '217',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-007-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 1,
        buyPrice: 50.0,
        sellPrice: 70.0,
      },
      {
        id: 'mtg-007-lp',
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        stock: 2,
        buyPrice: 38.0,
        sellPrice: 55.0,
      },
    ],
  },
  {
    id: 'mtg-008',
    name: 'Thoughtseize',
    setName: 'Theros',
    setCode: 'THS',
    number: '107',
    rarity: 'Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-008-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 4,
        buyPrice: 12.0,
        sellPrice: 18.0,
      },
    ],
  },
  {
    id: 'mtg-009',
    name: 'Arid Mesa',
    setName: 'Modern Horizons 2',
    setCode: 'MH2',
    number: '244',
    rarity: 'Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-009-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 3,
        buyPrice: 15.0,
        sellPrice: 22.0,
      },
      {
        id: 'mtg-009-mp',
        condition: CARD_CONDITIONS.MODERATELY_PLAYED,
        stock: 2,
        buyPrice: 10.0,
        sellPrice: 16.0,
      },
    ],
  },
  {
    id: 'mtg-010',
    name: 'Solitude',
    setName: 'Modern Horizons 2',
    setCode: 'MH2',
    number: '032',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-010-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 25.0,
        sellPrice: 38.0,
      },
    ],
  },
  {
    id: 'mtg-011',
    name: 'Fury',
    setName: 'Modern Horizons 2',
    setCode: 'MH2',
    number: '126',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-011-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 3,
        buyPrice: 8.0,
        sellPrice: 14.0,
      },
      {
        id: 'mtg-011-hp',
        condition: CARD_CONDITIONS.HEAVILY_PLAYED,
        stock: 1,
        buyPrice: 4.0,
        sellPrice: 7.0,
      },
    ],
  },
  {
    id: 'mtg-012',
    name: 'Orcish Bowmasters',
    setName: 'Lord of the Rings',
    setCode: 'LTR',
    number: '103',
    rarity: 'Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-012-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 35.0,
        sellPrice: 50.0,
      },
    ],
  },
  {
    id: 'mtg-013',
    name: 'Swords to Plowshares',
    setName: 'Iconic Masters',
    setCode: 'IMA',
    number: '036',
    rarity: 'Uncommon',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-013-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 8,
        buyPrice: 2.0,
        sellPrice: 4.0,
      },
      {
        id: 'mtg-013-dmg',
        condition: CARD_CONDITIONS.DAMAGED,
        stock: 3,
        buyPrice: 0.5,
        sellPrice: 1.5,
      },
    ],
  },
  {
    id: 'mtg-014',
    name: 'Brainstorm',
    setName: 'Conspiracy',
    setCode: 'CNS',
    number: '026',
    rarity: 'Common',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-014-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 15,
        buyPrice: 1.0,
        sellPrice: 2.0,
      },
    ],
  },
  {
    id: 'mtg-015',
    name: 'Collected Company',
    setName: 'Dragons of Tarkir',
    setCode: 'DTK',
    number: '177',
    rarity: 'Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-015-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 4,
        buyPrice: 10.0,
        sellPrice: 16.0,
      },
      {
        id: 'mtg-015-lp',
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        stock: 2,
        buyPrice: 7.0,
        sellPrice: 12.0,
      },
    ],
  },
  {
    id: 'mtg-016',
    name: 'Force of Negation',
    setName: 'Modern Horizons',
    setCode: 'MH1',
    number: '052',
    rarity: 'Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-016-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 30.0,
        sellPrice: 45.0,
      },
      {
        id: 'mtg-016-lp',
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        stock: 1,
        buyPrice: 22.0,
        sellPrice: 35.0,
      },
    ],
  },
  {
    id: 'mtg-017',
    name: 'Chalice of the Void',
    setName: 'Masters 25',
    setCode: 'A25',
    number: '222',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-017-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 1,
        buyPrice: 45.0,
        sellPrice: 65.0,
      },
    ],
  },
  {
    id: 'mtg-018',
    name: 'Path to Exile',
    setName: 'Conflux',
    setCode: 'CON',
    number: '015',
    rarity: 'Uncommon',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-018-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 10,
        buyPrice: 2.5,
        sellPrice: 4.5,
      },
      {
        id: 'mtg-018-mp',
        condition: CARD_CONDITIONS.MODERATELY_PLAYED,
        stock: 4,
        buyPrice: 1.5,
        sellPrice: 3.0,
      },
    ],
  },
  {
    id: 'mtg-019',
    name: 'Aether Vial',
    setName: 'Iconic Masters',
    setCode: 'IMA',
    number: '212',
    rarity: 'Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-019-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 3,
        buyPrice: 18.0,
        sellPrice: 28.0,
      },
    ],
  },
  {
    id: 'mtg-020',
    name: 'Liliana of the Veil',
    setName: 'Dominaria United',
    setCode: 'DMU',
    number: '097',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-020-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 8.0,
        sellPrice: 14.0,
      },
      {
        id: 'mtg-020-hp',
        condition: CARD_CONDITIONS.HEAVILY_PLAYED,
        stock: 1,
        buyPrice: 4.0,
        sellPrice: 7.0,
      },
    ],
  },
  {
    id: 'mtg-021',
    name: 'Scalding Tarn',
    setName: 'Modern Horizons 2',
    setCode: 'MH2',
    number: '254',
    rarity: 'Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-021-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 2,
        buyPrice: 20.0,
        sellPrice: 30.0,
      },
    ],
  },
  {
    id: 'mtg-022',
    name: 'Misty Rainforest',
    setName: 'Modern Horizons 2',
    setCode: 'MH2',
    number: '250',
    rarity: 'Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-022-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 3,
        buyPrice: 16.0,
        sellPrice: 25.0,
      },
      {
        id: 'mtg-022-lp',
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        stock: 2,
        buyPrice: 12.0,
        sellPrice: 19.0,
      },
    ],
  },
  {
    id: 'mtg-023',
    name: 'Endurance',
    setName: 'Modern Horizons 2',
    setCode: 'MH2',
    number: '157',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-023-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 4,
        buyPrice: 20.0,
        sellPrice: 32.0,
      },
    ],
  },
  {
    id: 'mtg-024',
    name: 'Delver of Secrets',
    setName: 'Innistrad',
    setCode: 'ISD',
    number: '051',
    rarity: 'Common',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-024-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 12,
        buyPrice: 0.5,
        sellPrice: 1.5,
      },
      {
        id: 'mtg-024-dmg',
        condition: CARD_CONDITIONS.DAMAGED,
        stock: 5,
        buyPrice: 0.1,
        sellPrice: 0.5,
      },
    ],
  },
  {
    id: 'mtg-025',
    name: 'Monastery Swiftspear',
    setName: 'Khans of Tarkir',
    setCode: 'KTK',
    number: '118',
    rarity: 'Uncommon',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    variants: [
      {
        id: 'mtg-025-nm',
        condition: CARD_CONDITIONS.NEAR_MINT,
        stock: 8,
        buyPrice: 1.0,
        sellPrice: 2.5,
      },
    ],
  },
];
