#!/bin/bash
# setup-mcp-config.sh — generate .devin/mcp_config.json for a repo.
#
# Resolves the codebase-memory-mcp binary via `command -v` and writes
# <repo>/.devin/mcp_config.json with the absolute path, so the file stays
# machine-local and does not need to be committed. Also ensures the repo's
# .gitignore ignores the generated file.
#
# Usage:
#   setup-mcp-config.sh              # the repo this script lives in
#   setup-mcp-config.sh <repo-path>  # a specific repo
#   setup-mcp-config.sh --all        # top-dev only: every .devin dir under projects/

set -euo pipefail

# Directory that contains this script's .devin/ (repo root or top-dev root).
SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

resolve_bin() {
  if ! command -v codebase-memory-mcp >/dev/null 2>&1; then
    echo "error: codebase-memory-mcp not found in PATH" >&2
    exit 1
  fi
  command -v codebase-memory-mcp
}

write_config() {
  local repo="$1" bin="$2"
  mkdir -p "$repo/.devin"
  cat > "$repo/.devin/mcp_config.json" <<EOF
{
  "mcpServers": {
    "codebase-memory-mcp": {
      "command": "$bin",
      "args": []
    }
  }
}
EOF
  echo "wrote $repo/.devin/mcp_config.json (command: $bin)"
}

ensure_gitignore() {
  local repo="$1"
  [ -d "$repo/.git" ] || return 0
  local gi="$repo/.gitignore" line=".devin/mcp_config.json"
  touch "$gi"
  if ! grep -qxF "$line" "$gi"; then
    printf '# Devin MCP config (machine-local, generated by setup-mcp-config.sh)\n%s\n' "$line" >> "$gi"
    echo "  .gitignore += $line"
  fi
}

BIN="$(resolve_bin)"

case "${1:-}" in
  --all)
    if [ ! -d "$SCRIPT_ROOT/projects" ]; then
      echo "warn: --all is only meaningful from the top-dev copy; no projects/ dir under $SCRIPT_ROOT — configuring this repo only" >&2
    fi
    write_config "$SCRIPT_ROOT" "$BIN"
    ensure_gitignore "$SCRIPT_ROOT"
    if [ -d "$SCRIPT_ROOT/projects" ]; then
      while IFS= read -r devin_dir; do
        repo="$(dirname "$devin_dir")"
        write_config "$repo" "$BIN"
        ensure_gitignore "$repo"
      done < <(find "$SCRIPT_ROOT/projects" -maxdepth 4 -type d -name ".devin" | sort)
    fi
    ;;
  "")
    write_config "$SCRIPT_ROOT" "$BIN"
    ensure_gitignore "$SCRIPT_ROOT"
    ;;
  *)
    TARGET="$(cd "$1" && pwd)"
    write_config "$TARGET" "$BIN"
    ensure_gitignore "$TARGET"
    ;;
esac
