query BuyerBudget($buyerGuid: String!, $tcg: String!) {
  buyerBudget(buyerGuid: $buyerGuid, tcg: $tcg) {
    guid
    tcg
    assignedAmount
    usedAmount
    utilization
    buyer {
      guid
      name
      emailAddress
    }
    createdDate
    updatedDate
  }
}

query BuyerBudgets($tcg: String) {
  buyerBudgets(tcg: $tcg) {
    guid
    tcg
    assignedAmount
    usedAmount
    utilization
    buyer {
      guid
      name
      emailAddress
    }
    createdDate
    updatedDate
  }
}

mutation UpdateBuyerBudget($updateBuyerBudgetInput: UpdateBuyerBudgetInput!) {
  updateBuyerBudget(updateBuyerBudgetInput: $updateBuyerBudgetInput) {
    guid
    tcg
    assignedAmount
    usedAmount
    utilization
    buyer {
      guid
      name
      emailAddress
    }
    createdDate
    updatedDate
  }
}
