query MagicCardInternalList($findMagicCardsPublicArgs: FindMagicCardsPublicArgs!) {
  magicCardInternalList(findMagicCardsPublicArgs: $findMagicCardsPublicArgs) {
    data {
      guid
      name
      language
      edition
      collectorNumber
      isFoil
      sellPrice
      availableStock
      totalStock
      imageUri
      inventoryCards {
        guid
        condition
        language
        stock
        purchasePrice
        sellPrice
      }
    }
    count
  }
}

query MagicCardInternalDetail($guid: String!) {
  magicCardInternalDetail(guid: $guid) {
    guid
    name
    language
    edition
    collectorNumber
    isFoil
    rarity
    sellPrice
    totalStock
    imageUri
    inventoryCards {
      guid
      condition
      language
      stock
      purchasePrice
      sellPrice
    }
  }
}

query MagicCardCollections {
  magicCardCollections {
    guid
    name
    editionIconUri
  }
}

query MagicCardRarities {
  magicCardRarities
}

query MagicCardWithMetrics($guid: String!) {
  magicCardWithMetrics(guid: $guid) {
    variantsMetrics {
      condition
      stock
      lastSellDate
      avgDaysInInventory
      wishlistCount
    }
    priceRetail
    priceBuy
  }
}

query MagicBatchCardSearch($input: BatchSearchMagicCardsInput!) {
  magicBatchCardSearch(input: $input) {
    results {
    originalLine
    parsedQuantity
    parsedName
    parsedSet
    parsedNumber
    bestMatch {
      guid
      name
      language
      edition
      collectorNumber
      imageUri
      isFoil
      sellPrice
      totalStock
      cardMetrics {
        variantsMetrics {
          condition
          stock
          lastSellDate
          avgDaysInInventory
          wishlistCount
        }
        priceRetail
        priceBuy
      }
    }
    relatedCards {
      guid
      name
      language
      edition
      collectorNumber
      imageUri
      isFoil
      sellPrice
      totalStock
    }
    error
    }
  }
}
