query GetProfileVariants($findProfilesArgs: FindProfilesArgs!) {
  getProfileVariants(findProfilesArgs: $findProfilesArgs) {
    count
    data {
      createdDate
      guid
      size
      updatedDate
      stock {
        guid
        minStock
        stock
      }
      profileGroup {
        category
        color
        guid
        name
        line
        price
        sku
        supplier
        createdDate
        updatedDate
      }
    }
  }
}

query GetChapes($findChapesArgs: FindChapesArgs!) {
  getChapes(findChapesArgs: $findChapesArgs) {
    count
    data {
      category
      color
      createdDate
      guid
      line
      name
      price
      sku
      supplier
      unitMeasure
      updatedDate
      stock {
        guid
        minStock
        stock
      }
    }
  }
}

query GetGlasses($findGlassesArgs: FindGlassesArgs!) {
  getGlasses(findGlassesArgs: $findGlassesArgs) {
    count
    data {
      category
      guid
      name
      price
      sku
      thickness
      stock {
        minStock
        stock
      }
    }
  }
}

mutation CreateProfile($createProfileInput: CreateProfileInput!) {
  createProfile(createProfileInput: $createProfileInput) {
    guid
  }
}

mutation CreateChape($createChapeInput: CreateChapeInput!) {
  createChape(createChapeInput: $createChapeInput) {
    guid
  }
}

mutation CreateGlass($createGlassInput: CreateGlassInput!) {
  createGlass(createGlassInput: $createGlassInput) {
    guid
  }
}
