mutation Login($loginUserInput: LoginUserInput!) {
  login(loginUserInput: $loginUserInput) {
    access_token
    credentials_expired_token
    user {
      active
      emailAddress
      guid
      name
      role
    }
  }
}
