mutation RequestPasswordChange($requestPasswordChangeInput: RequestPasswordChangeInput!) {
  requestPasswordChange(requestPasswordChangeInput: $requestPasswordChangeInput) {
    success
  }
}

mutation ChangePassword($changePasswordInput: ChangePasswordInput!) {
  changePassword(changePasswordInput: $changePasswordInput) {
    success
  }
}
