query SelectGlasses($selectGlassesArgs: SelectGlassesArgs!) {
  selectGlasses(selectGlassesArgs: $selectGlassesArgs) {
    count
    data {
      guid
      name
      sku
      thickness
    }
  }
}

query SelectProfiles($selectProfilesArgs: SelectProfilesArgs!) {
  selectProfiles(selectProfilesArgs: $selectProfilesArgs) {
    count
    data {
      guid
      name
      sku
    }
  }
}

query SelectChapes($selectChapesArgs: SelectChapesArgs!) {
  selectChapes(selectChapesArgs: $selectChapesArgs) {
    count
    data {
      guid
      line
      name
      sku
      unitMeasure
    }
  }
}
