import { FULFILLMENT_STATUS, ISale, SALE_STATUS } from '../../domain/types';
import { CARD_CONDITIONS } from '@/lib/types/card.types';
import { TCG_TYPES } from '@/lib/types/tcg.types';

const MOCK_EMAIL_DELAY_MS = 1500;

export const sendReadyForPickupEmail = async (
  customerEmail: string,
  saleCode: string
): Promise<{ success: boolean }> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      console.log(
        `[MOCK] Email "listo para recolección" enviado a ${customerEmail} para pedido ${saleCode}`
      );
      resolve({ success: true });
    }, MOCK_EMAIL_DELAY_MS);
  });
};

export const MOCK_SALES: ISale[] = [
  {
    id: 'sale-001',
    code: 'KSP-A1B2C3',
    status: SALE_STATUS.NEW,
    tcgType: TCG_TYPES.POKEMON,
    customerId: 'cust-001',
    customerName: 'Carlos Mendoza',
    customerEmail: 'carlos@example.com',
    notes: 'Pedido desde carpeta digital',
    createdAt: '2025-06-10T14:30:00Z',
    updatedAt: '2025-06-10T14:30:00Z',
    items: [
      {
        id: 'si-001',
        cardId: 'pkmn-001',
        cardName: 'Charizard ex',
        cardImageUrl: 'https://storage.googleapis.com/images.pricecharting.com/83e642af4338affb9d77be8d84c9a29d3bb5c3a1909ab4428ce2651365c62d97/240.jpg',
        setName: 'Obsidian Flames',
        setCode: 'OBF',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 65.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-002',
        cardId: 'pkmn-002',
        cardName: 'Pikachu VMAX',
        cardImageUrl: 'https://images.pokemontcg.io/swsh4/44_hires.png',
        setName: 'Vivid Voltage',
        setCode: 'VIV',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 30.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
    ],
  },
  {
    id: 'sale-002',
    code: 'KSP-D4E5F6',
    status: SALE_STATUS.IN_PROGRESS,
    tcgType: TCG_TYPES.POKEMON,
    customerId: 'cust-002',
    customerName: 'Ana García',
    customerEmail: 'ana@example.com',
    createdAt: '2025-06-09T10:15:00Z',
    updatedAt: '2025-06-09T11:00:00Z',
    items: [
      {
        id: 'si-003',
        cardId: 'pkmn-004',
        cardName: 'Umbreon VMAX',
        cardImageUrl: 'https://images.pokemontcg.io/swsh7/95_hires.png',
        setName: 'Evolving Skies',
        setCode: 'EVS',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 250.0,
        foundQuantity: 1,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
    ],
  },
  {
    id: 'sale-003',
    code: 'KSP-G7H8I9',
    status: SALE_STATUS.READY_FOR_PICKUP,
    tcgType: TCG_TYPES.POKEMON,
    customerId: 'cust-003',
    customerName: 'Roberto Sánchez',
    customerEmail: 'roberto@example.com',
    notes: 'Cliente VIP - prioridad alta',
    createdAt: '2025-06-08T16:45:00Z',
    updatedAt: '2025-06-09T09:30:00Z',
    items: [
      {
        id: 'si-004',
        cardId: 'pkmn-008',
        cardName: 'Rayquaza VMAX',
        cardImageUrl: 'https://images.pokemontcg.io/swsh7/218_hires.png',
        setName: 'Evolving Skies',
        setCode: 'EVS',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 120.0,
        foundQuantity: 1,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
      {
        id: 'si-005',
        cardId: 'pkmn-005',
        cardName: 'Gardevoir ex',
        cardImageUrl: 'https://images.pokemontcg.io/sv1/86_hires.png',
        setName: 'Scarlet & Violet',
        setCode: 'SVI',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 2,
        unitPrice: 8.0,
        foundQuantity: 2,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
    ],
  },
  {
    id: 'sale-004',
    code: 'KSP-J1K2L3',
    status: SALE_STATUS.COMPLETED,
    tcgType: TCG_TYPES.POKEMON,
    customerId: 'cust-001',
    customerName: 'Carlos Mendoza',
    customerEmail: 'carlos@example.com',
    createdAt: '2025-06-05T12:00:00Z',
    updatedAt: '2025-06-06T14:20:00Z',
    items: [
      {
        id: 'si-006',
        cardId: 'pkmn-010',
        cardName: 'Arceus VSTAR',
        cardImageUrl: 'https://images.pokemontcg.io/swsh9/123_hires.png',
        setName: 'Brilliant Stars',
        setCode: 'BRS',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 22.0,
        foundQuantity: 1,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
    ],
  },
  {
    id: 'sale-005',
    code: 'KSP-M4N5O6',
    status: SALE_STATUS.CANCELLED,
    tcgType: TCG_TYPES.POKEMON,
    customerId: 'cust-004',
    customerName: 'Laura Martínez',
    customerEmail: 'laura@example.com',
    notes: 'Cliente no se presentó a recoger',
    createdAt: '2025-06-04T09:00:00Z',
    updatedAt: '2025-06-07T18:00:00Z',
    items: [
      {
        id: 'si-007',
        cardId: 'pkmn-009',
        cardName: 'Mew VMAX',
        cardImageUrl: 'https://images.pokemontcg.io/swsh8/269_hires.png',
        setName: 'Fusion Strike',
        setCode: 'FST',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.MODERATELY_PLAYED,
        quantity: 1,
        unitPrice: 28.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.NOT_AVAILABLE,
      },
    ],
  },
  {
    id: 'sale-006',
    code: 'KSP-P7Q8R9',
    status: SALE_STATUS.NEW,
    tcgType: TCG_TYPES.MAGIC,
    customerId: 'cust-005',
    customerName: 'Diego Torres',
    customerEmail: 'diego@example.com',
    createdAt: '2025-06-10T08:00:00Z',
    updatedAt: '2025-06-10T08:00:00Z',
    items: [
      {
        id: 'si-008',
        cardId: 'mtg-003',
        cardName: 'Sheoldred, the Apocalypse',
        cardImageUrl: 'https://cards.scryfall.io/large/front/d/6/d67be074-cdd4-41d9-ac89-0a0456c4e4b2.jpg',
        setName: 'Dominaria United',
        setCode: 'DMU',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 95.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-009',
        cardId: 'mtg-001',
        cardName: 'Lightning Bolt',
        cardImageUrl: 'https://cards.scryfall.io/large/front/9/5/9521375e-0bc1-45ef-b513-6d332a25f9d2.jpg',
        setName: 'Fourth Edition',
        setCode: '4ED',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 4,
        unitPrice: 2.5,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
    ],
  },
  {
    id: 'sale-007',
    code: 'KSP-S1T2U3',
    status: SALE_STATUS.IN_PROGRESS,
    tcgType: TCG_TYPES.MAGIC,
    customerId: 'cust-006',
    customerName: 'Fernanda López',
    customerEmail: 'fernanda@example.com',
    notes: 'Pedido urgente para torneo',
    createdAt: '2025-06-09T17:30:00Z',
    updatedAt: '2025-06-10T09:00:00Z',
    items: [
      {
        id: 'si-010',
        cardId: 'mtg-002',
        cardName: 'Ragavan, Nimble Pilferer',
        cardImageUrl: 'https://cards.scryfall.io/large/front/a/9/a9738cda-adb1-47fb-9f4c-ecd930228c4d.jpg',
        setName: 'Modern Horizons 2',
        setCode: 'MH2',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 75.0,
        foundQuantity: 2,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
      {
        id: 'si-011',
        cardId: 'mtg-005',
        cardName: 'The One Ring',
        cardImageUrl: 'https://cards.scryfall.io/large/front/d/5/d5806e68-1054-458e-866d-1f2470f682b2.jpg',
        setName: 'Lord of the Rings',
        setCode: 'LTR',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 60.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.NOT_AVAILABLE,
      },
    ],
  },
  {
    id: 'sale-008',
    code: 'KSP-V4W5X6',
    status: SALE_STATUS.READY_FOR_PICKUP,
    tcgType: TCG_TYPES.MAGIC,
    customerId: 'cust-007',
    customerName: 'Miguel Ángel Ruiz',
    customerEmail: 'miguel@example.com',
    createdAt: '2025-06-08T11:00:00Z',
    updatedAt: '2025-06-09T15:45:00Z',
    items: [
      {
        id: 'si-012',
        cardId: 'mtg-007',
        cardName: 'Wrenn and Six',
        cardImageUrl: 'https://cards.scryfall.io/large/front/4/a/4a706ecf-3277-40e3-871c-4ba4ead16e20.jpg',
        setName: 'Modern Horizons',
        setCode: 'MH1',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 1,
        unitPrice: 55.0,
        foundQuantity: 1,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
    ],
  },
  {
    id: 'sale-009',
    code: 'KSP-Y7Z8A1',
    status: SALE_STATUS.COMPLETED,
    tcgType: TCG_TYPES.MAGIC,
    customerId: 'cust-005',
    customerName: 'Diego Torres',
    customerEmail: 'diego@example.com',
    createdAt: '2025-06-03T13:00:00Z',
    updatedAt: '2025-06-04T10:30:00Z',
    items: [
      {
        id: 'si-013',
        cardId: 'mtg-012',
        cardName: 'Orcish Bowmasters',
        cardImageUrl: 'https://cards.scryfall.io/large/front/7/c/7c024bae-5631-4e20-ac69-df392ac9e109.jpg',
        setName: 'Lord of the Rings',
        setCode: 'LTR',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 50.0,
        foundQuantity: 2,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
      {
        id: 'si-014',
        cardId: 'mtg-006',
        cardName: 'Fatal Push',
        cardImageUrl: 'https://cards.scryfall.io/large/front/b/5/b5e81649-9954-424c-89d1-f87d73b66047.jpg',
        setName: 'Aether Revolt',
        setCode: 'AER',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 5.0,
        foundQuantity: 4,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
    ],
  },
  {
    id: 'sale-010',
    code: 'KSP-B2C3D4',
    status: SALE_STATUS.CANCELLED,
    tcgType: TCG_TYPES.MAGIC,
    customerId: 'cust-008',
    customerName: 'Patricia Vega',
    customerEmail: 'patricia@example.com',
    notes: 'Cancelado por cliente - fuera de zona de entrega',
    createdAt: '2025-06-02T15:00:00Z',
    updatedAt: '2025-06-03T08:00:00Z',
    items: [
      {
        id: 'si-015',
        cardId: 'mtg-017',
        cardName: 'Chalice of the Void',
        cardImageUrl: 'https://cards.scryfall.io/large/front/1/f/1f0d2e8e-c8f2-4b31-a6ba-6283fc8740d4.jpg',
        setName: 'Masters 25',
        setCode: 'A25',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 65.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
    ],
  },
  {
    id: 'sale-011',
    code: 'KSP-E5F6G7',
    status: SALE_STATUS.IN_PROGRESS,
    tcgType: TCG_TYPES.POKEMON,
    customerId: 'cust-009',
    customerName: 'Alejandro Reyes',
    customerEmail: 'alejandro@example.com',
    notes: 'Pedido grande - torneo regional',
    createdAt: '2025-06-11T09:00:00Z',
    updatedAt: '2025-06-11T10:30:00Z',
    items: [
      {
        id: 'si-016',
        cardId: 'pkmn-020',
        cardName: 'Lugia VSTAR',
        cardImageUrl: 'https://images.pokemontcg.io/swsh12pt5/139_hires.png',
        setName: 'Crown Zenith',
        setCode: 'CRZ',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 18.0,
        foundQuantity: 2,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
      {
        id: 'si-017',
        cardId: 'pkmn-021',
        cardName: 'Giratina VSTAR',
        cardImageUrl: 'https://images.pokemontcg.io/swsh11/131_hires.png',
        setName: 'Lost Origin',
        setCode: 'LOR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 12.0,
        foundQuantity: 1,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
      {
        id: 'si-018',
        cardId: 'pkmn-022',
        cardName: 'Palkia VSTAR',
        cardImageUrl: 'https://images.pokemontcg.io/swsh10/040_hires.png',
        setName: 'Astral Radiance',
        setCode: 'ASR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 3,
        unitPrice: 8.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-019',
        cardId: 'pkmn-023',
        cardName: 'Mewtwo VSTAR',
        cardImageUrl: 'https://images.pokemontcg.io/swsh11/079_hires.png',
        setName: 'Lost Origin',
        setCode: 'LOR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 5.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-020',
        cardId: 'pkmn-024',
        cardName: 'Origin Forme Dialga VSTAR',
        cardImageUrl: 'https://images.pokemontcg.io/swsh10/114_hires.png',
        setName: 'Astral Radiance',
        setCode: 'ASR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 6.0,
        foundQuantity: 2,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
      {
        id: 'si-021',
        cardId: 'pkmn-025',
        cardName: 'Mew VMAX',
        cardImageUrl: 'https://images.pokemontcg.io/swsh8/269_hires.png',
        setName: 'Fusion Strike',
        setCode: 'FST',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 28.0,
        foundQuantity: 1,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
      {
        id: 'si-022',
        cardId: 'pkmn-026',
        cardName: 'Arceus VSTAR',
        cardImageUrl: 'https://images.pokemontcg.io/swsh9/123_hires.png',
        setName: 'Brilliant Stars',
        setCode: 'BRS',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 2,
        unitPrice: 22.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-023',
        cardId: 'pkmn-027',
        cardName: 'Charizard ex',
        cardImageUrl: 'https://images.pokemontcg.io/sv3/234_hires.png',
        setName: 'Obsidian Flames',
        setCode: 'OBF',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 65.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.NOT_AVAILABLE,
      },
      {
        id: 'si-024',
        cardId: 'pkmn-028',
        cardName: 'Miraidon ex',
        cardImageUrl: 'https://images.pokemontcg.io/sv1/81_hires.png',
        setName: 'Scarlet & Violet',
        setCode: 'SVI',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 10.0,
        foundQuantity: 2,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
      {
        id: 'si-025',
        cardId: 'pkmn-029',
        cardName: 'Koraidon ex',
        cardImageUrl: 'https://images.pokemontcg.io/sv1/125_hires.png',
        setName: 'Scarlet & Violet',
        setCode: 'SVI',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 9.0,
        foundQuantity: 1,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
      {
        id: 'si-026',
        cardId: 'pkmn-030',
        cardName: 'Ting-Lu ex',
        cardImageUrl: 'https://images.pokemontcg.io/sv2/127_hires.png',
        setName: 'Paldea Evolved',
        setCode: 'PAL',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.MODERATELY_PLAYED,
        quantity: 4,
        unitPrice: 3.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-027',
        cardId: 'pkmn-031',
        cardName: 'Chien-Pao ex',
        cardImageUrl: 'https://images.pokemontcg.io/sv2/061_hires.png',
        setName: 'Paldea Evolved',
        setCode: 'PAL',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 7.0,
        foundQuantity: 2,
        fulfillmentStatus: FULFILLMENT_STATUS.FOUND,
      },
    ],
  },
  {
    id: 'sale-012',
    code: 'KSP-H8I9J0',
    status: SALE_STATUS.NEW,
    tcgType: TCG_TYPES.MAGIC,
    customerId: 'cust-010',
    customerName: 'Valentina Cruz',
    customerEmail: 'valentina@example.com',
    notes: 'Pedido para deck competitivo Modern',
    createdAt: '2025-06-12T14:00:00Z',
    updatedAt: '2025-06-12T14:00:00Z',
    items: [
      {
        id: 'si-028',
        cardId: 'mtg-020',
        cardName: 'Ragavan, Nimble Pilferer',
        cardImageUrl: 'https://cards.scryfall.io/large/front/a/9/a9738cda-adb1-47fb-9f4c-ecd930228c4d.jpg',
        setName: 'Modern Horizons 2',
        setCode: 'MH2',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 75.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-029',
        cardId: 'mtg-021',
        cardName: 'Wrenn and Six',
        cardImageUrl: 'https://cards.scryfall.io/large/front/4/a/4a706ecf-3277-40e3-871c-4ba4ead16e20.jpg',
        setName: 'Modern Horizons',
        setCode: 'MH1',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 55.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-030',
        cardId: 'mtg-022',
        cardName: 'Sheoldred, the Apocalypse',
        cardImageUrl: 'https://cards.scryfall.io/large/front/d/6/d67be074-cdd4-41d9-ac89-0a0456c4e4b2.jpg',
        setName: 'Dominaria United',
        setCode: 'DMU',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 3,
        unitPrice: 95.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-031',
        cardId: 'mtg-023',
        cardName: 'The One Ring',
        cardImageUrl: 'https://cards.scryfall.io/large/front/d/5/d5806e68-1054-458e-866d-1f2470f682b2.jpg',
        setName: 'Lord of the Rings',
        setCode: 'LTR',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 1,
        unitPrice: 60.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-032',
        cardId: 'mtg-024',
        cardName: 'Orcish Bowmasters',
        cardImageUrl: 'https://cards.scryfall.io/large/front/7/c/7c024bae-5631-4e20-ac69-df392ac9e109.jpg',
        setName: 'Lord of the Rings',
        setCode: 'LTR',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 50.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-033',
        cardId: 'mtg-025',
        cardName: 'Fury',
        cardImageUrl: 'https://cards.scryfall.io/large/front/b/d/bd281158-8180-40b9-a5b7-03cfc712d81a.jpg',
        setName: 'Modern Horizons 2',
        setCode: 'MH2',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 35.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-034',
        cardId: 'mtg-026',
        cardName: 'Solitude',
        cardImageUrl: 'https://cards.scryfall.io/large/front/4/7/47a6234f-309f-4e03-9263-66da48b57571.jpg',
        setName: 'Modern Horizons 2',
        setCode: 'MH2',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 3,
        unitPrice: 28.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-035',
        cardId: 'mtg-027',
        cardName: 'Endurance',
        cardImageUrl: 'https://cards.scryfall.io/large/front/e/b/eb0e0404-4846-4891-acfa-bd0951b6a571.jpg',
        setName: 'Modern Horizons 2',
        setCode: 'MH2',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 32.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-036',
        cardId: 'mtg-028',
        cardName: 'Subtlety',
        cardImageUrl: 'https://cards.scryfall.io/large/front/7/0/701256d5-1389-48b7-9571-f54571502e17.jpg',
        setName: 'Modern Horizons 2',
        setCode: 'MH2',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 8.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-037',
        cardId: 'mtg-029',
        cardName: 'Grief',
        cardImageUrl: 'https://cards.scryfall.io/large/front/e/6/e6befbc4-1320-4f26-bd9f-b1814571571a.jpg',
        setName: 'Modern Horizons 2',
        setCode: 'MH2',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.MODERATELY_PLAYED,
        quantity: 4,
        unitPrice: 15.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-038',
        cardId: 'mtg-030',
        cardName: 'Murktide Regent',
        cardImageUrl: 'https://cards.scryfall.io/large/front/2/0/20c4aac1-bb8d-4bc5-aa42-250cec21d806.jpg',
        setName: 'Modern Horizons 2',
        setCode: 'MH2',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 22.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-039',
        cardId: 'mtg-031',
        cardName: 'Prismatic Ending',
        cardImageUrl: 'https://cards.scryfall.io/large/front/8/2/825969b9-3c70-4571-a5c3-7f23b5e4a8f6.jpg',
        setName: 'Modern Horizons 2',
        setCode: 'MH2',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 2.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-040',
        cardId: 'mtg-032',
        cardName: 'Unholy Heat',
        cardImageUrl: 'https://cards.scryfall.io/large/front/2/b/2b73d294-6ab1-4051-9b0f-d8e335d37674.jpg',
        setName: 'Modern Horizons 2',
        setCode: 'MH2',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 1.5,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-041',
        cardId: 'mtg-033',
        cardName: 'Counterspell',
        cardImageUrl: 'https://cards.scryfall.io/large/front/1/9/1920c827-e622-48a5-9929-e0e8e3a3fc55.jpg',
        setName: 'Modern Horizons 2',
        setCode: 'MH2',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 3.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-042',
        cardId: 'mtg-034',
        cardName: 'Chalice of the Void',
        cardImageUrl: 'https://cards.scryfall.io/large/front/1/f/1f0d2e8e-c8f2-4b31-a6ba-6283fc8740d4.jpg',
        setName: 'Masters 25',
        setCode: 'A25',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 2,
        unitPrice: 65.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
    ],
  },
  {
    id: 'sale-013',
    code: 'KSP-LB0X01',
    status: SALE_STATUS.NEW,
    tcgType: TCG_TYPES.POKEMON,
    customerId: 'cust-011',
    customerName: 'Sebastián Herrera',
    customerEmail: 'sebastian@example.com',
    notes: 'Deck completo Giratina Lost Box - torneo regional',
    createdAt: '2025-06-13T10:00:00Z',
    updatedAt: '2025-06-13T10:00:00Z',
    items: [
      {
        id: 'si-100',
        cardId: 'pkmn-100',
        cardName: 'Giratina VSTAR',
        cardImageUrl: 'https://images.pokemontcg.io/swsh11/131_hires.png',
        setName: 'Lost Origin',
        setCode: 'LOR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 12.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-101',
        cardId: 'pkmn-101',
        cardName: 'Giratina V',
        cardImageUrl: 'https://images.pokemontcg.io/swsh11/130_hires.png',
        setName: 'Lost Origin',
        setCode: 'LOR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 4.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-102',
        cardId: 'pkmn-102',
        cardName: 'Comfey',
        cardImageUrl: 'https://images.pokemontcg.io/swsh11/079_hires.png',
        setName: 'Lost Origin',
        setCode: 'LOR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 2.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-103',
        cardId: 'pkmn-103',
        cardName: 'Sableye',
        cardImageUrl: 'https://images.pokemontcg.io/swsh11/070_hires.png',
        setName: 'Lost Origin',
        setCode: 'LOR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 1.5,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-104',
        cardId: 'pkmn-104',
        cardName: 'Cramorant',
        cardImageUrl: 'https://images.pokemontcg.io/swsh11/050_hires.png',
        setName: 'Lost Origin',
        setCode: 'LOR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 1.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-105',
        cardId: 'pkmn-105',
        cardName: 'Dragonite V',
        cardImageUrl: 'https://images.pokemontcg.io/swsh12pt5/049_hires.png',
        setName: 'Crown Zenith',
        setCode: 'CRZ',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 3.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-106',
        cardId: 'pkmn-106',
        cardName: 'Radiant Greninja',
        cardImageUrl: 'https://images.pokemontcg.io/swsh10/046_hires.png',
        setName: 'Astral Radiance',
        setCode: 'ASR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 5.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-107',
        cardId: 'pkmn-107',
        cardName: 'Manaphy',
        cardImageUrl: 'https://images.pokemontcg.io/swsh9/041_hires.png',
        setName: 'Brilliant Stars',
        setCode: 'BRS',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 2.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-108',
        cardId: 'pkmn-108',
        cardName: 'Colress\'s Experiment',
        cardImageUrl: 'https://images.pokemontcg.io/swsh11/155_hires.png',
        setName: 'Lost Origin',
        setCode: 'LOR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 1.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-109',
        cardId: 'pkmn-109',
        cardName: 'Battle VIP Pass',
        cardImageUrl: 'https://images.pokemontcg.io/swsh8/225_hires.png',
        setName: 'Fusion Strike',
        setCode: 'FST',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 8.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-110',
        cardId: 'pkmn-110',
        cardName: 'Mirage Gate',
        cardImageUrl: 'https://images.pokemontcg.io/swsh11/163_hires.png',
        setName: 'Lost Origin',
        setCode: 'LOR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 3.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-111',
        cardId: 'pkmn-111',
        cardName: 'Nest Ball',
        cardImageUrl: 'https://images.pokemontcg.io/sv1/181_hires.png',
        setName: 'Scarlet & Violet',
        setCode: 'SVI',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 1.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-112',
        cardId: 'pkmn-112',
        cardName: 'Switch Cart',
        cardImageUrl: 'https://images.pokemontcg.io/swsh10/154_hires.png',
        setName: 'Astral Radiance',
        setCode: 'ASR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 3,
        unitPrice: 0.5,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-113',
        cardId: 'pkmn-113',
        cardName: 'Escape Rope',
        cardImageUrl: 'https://images.pokemontcg.io/swsh9/125_hires.png',
        setName: 'Brilliant Stars',
        setCode: 'BRS',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 2,
        unitPrice: 1.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-114',
        cardId: 'pkmn-114',
        cardName: 'Lost Vacuum',
        cardImageUrl: 'https://images.pokemontcg.io/swsh11/162_hires.png',
        setName: 'Lost Origin',
        setCode: 'LOR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 2.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-115',
        cardId: 'pkmn-115',
        cardName: 'Akari\'s Focus',
        cardImageUrl: 'https://images.pokemontcg.io/swsh10/150_hires.png',
        setName: 'Astral Radiance',
        setCode: 'ASR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 0.5,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-116',
        cardId: 'pkmn-116',
        cardName: 'Boss\'s Orders',
        cardImageUrl: 'https://images.pokemontcg.io/swsh9/132_hires.png',
        setName: 'Brilliant Stars',
        setCode: 'BRS',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 3.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-117',
        cardId: 'pkmn-117',
        cardName: 'Roxanne',
        cardImageUrl: 'https://images.pokemontcg.io/swsh10/150_hires.png',
        setName: 'Astral Radiance',
        setCode: 'ASR',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 1.5,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-118',
        cardId: 'pkmn-118',
        cardName: 'Path to the Peak',
        cardImageUrl: 'https://images.pokemontcg.io/swsh6/148_hires.png',
        setName: 'Chilling Reign',
        setCode: 'CRE',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 1.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-119',
        cardId: 'pkmn-119',
        cardName: 'Jet Energy',
        cardImageUrl: 'https://images.pokemontcg.io/sv2/190_hires.png',
        setName: 'Paldea Evolved',
        setCode: 'PAL',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 2.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-120',
        cardId: 'pkmn-120',
        cardName: 'Psychic Energy',
        cardImageUrl: 'https://images.pokemontcg.io/sve/5_hires.png',
        setName: 'Scarlet & Violet Energies',
        setCode: 'SVE',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 0.25,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-121',
        cardId: 'pkmn-121',
        cardName: 'Grass Energy',
        cardImageUrl: 'https://images.pokemontcg.io/sve/1_hires.png',
        setName: 'Scarlet & Violet Energies',
        setCode: 'SVE',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 0.25,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
      {
        id: 'si-122',
        cardId: 'pkmn-122',
        cardName: 'V Guard Energy',
        cardImageUrl: 'https://images.pokemontcg.io/swsh12/169_hires.png',
        setName: 'Silver Tempest',
        setCode: 'SIT',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 1.0,
        foundQuantity: 0,
        fulfillmentStatus: FULFILLMENT_STATUS.PENDING,
      },
    ],
  },
];
