import { ISale, SALE_STATUS } from '../../domain/types';
import { CARD_CONDITIONS } from '@/lib/types/card.types';
import { TCG_TYPES } from '@/lib/types/tcg.types';

export const MOCK_SALES: ISale[] = [
  {
    id: 'sale-001',
    code: 'KSP-A1B2C3',
    status: SALE_STATUS.NEW,
    tcgType: TCG_TYPES.POKEMON,
    customerId: 'cust-001',
    customerName: 'Carlos Mendoza',
    customerEmail: 'carlos@example.com',
    notes: 'Pedido desde carpeta digital',
    createdAt: '2025-06-10T14:30:00Z',
    updatedAt: '2025-06-10T14:30:00Z',
    items: [
      {
        id: 'si-001',
        cardId: 'pkmn-001',
        cardName: 'Charizard ex',
        cardImageUrl: 'https://storage.googleapis.com/images.pricecharting.com/83e642af4338affb9d77be8d84c9a29d3bb5c3a1909ab4428ce2651365c62d97/240.jpg',
        setName: 'Obsidian Flames',
        setCode: 'OBF',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 65.0,
      },
      {
        id: 'si-002',
        cardId: 'pkmn-002',
        cardName: 'Pikachu VMAX',
        cardImageUrl: 'https://images.pokemontcg.io/swsh4/44_hires.png',
        setName: 'Vivid Voltage',
        setCode: 'VIV',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 30.0,
      },
    ],
  },
  {
    id: 'sale-002',
    code: 'KSP-D4E5F6',
    status: SALE_STATUS.IN_PROGRESS,
    tcgType: TCG_TYPES.POKEMON,
    customerId: 'cust-002',
    customerName: 'Ana García',
    customerEmail: 'ana@example.com',
    createdAt: '2025-06-09T10:15:00Z',
    updatedAt: '2025-06-09T11:00:00Z',
    items: [
      {
        id: 'si-003',
        cardId: 'pkmn-004',
        cardName: 'Umbreon VMAX',
        cardImageUrl: 'https://images.pokemontcg.io/swsh7/95_hires.png',
        setName: 'Evolving Skies',
        setCode: 'EVS',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 250.0,
      },
    ],
  },
  {
    id: 'sale-003',
    code: 'KSP-G7H8I9',
    status: SALE_STATUS.READY_FOR_PICKUP,
    tcgType: TCG_TYPES.POKEMON,
    customerId: 'cust-003',
    customerName: 'Roberto Sánchez',
    customerEmail: 'roberto@example.com',
    notes: 'Cliente VIP - prioridad alta',
    createdAt: '2025-06-08T16:45:00Z',
    updatedAt: '2025-06-09T09:30:00Z',
    items: [
      {
        id: 'si-004',
        cardId: 'pkmn-008',
        cardName: 'Rayquaza VMAX',
        cardImageUrl: 'https://images.pokemontcg.io/swsh7/218_hires.png',
        setName: 'Evolving Skies',
        setCode: 'EVS',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 120.0,
      },
      {
        id: 'si-005',
        cardId: 'pkmn-005',
        cardName: 'Gardevoir ex',
        cardImageUrl: 'https://images.pokemontcg.io/sv1/86_hires.png',
        setName: 'Scarlet & Violet',
        setCode: 'SVI',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 2,
        unitPrice: 8.0,
      },
    ],
  },
  {
    id: 'sale-004',
    code: 'KSP-J1K2L3',
    status: SALE_STATUS.COMPLETED,
    tcgType: TCG_TYPES.POKEMON,
    customerId: 'cust-001',
    customerName: 'Carlos Mendoza',
    customerEmail: 'carlos@example.com',
    createdAt: '2025-06-05T12:00:00Z',
    updatedAt: '2025-06-06T14:20:00Z',
    items: [
      {
        id: 'si-006',
        cardId: 'pkmn-010',
        cardName: 'Arceus VSTAR',
        cardImageUrl: 'https://images.pokemontcg.io/swsh9/123_hires.png',
        setName: 'Brilliant Stars',
        setCode: 'BRS',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 22.0,
      },
    ],
  },
  {
    id: 'sale-005',
    code: 'KSP-M4N5O6',
    status: SALE_STATUS.CANCELLED,
    tcgType: TCG_TYPES.POKEMON,
    customerId: 'cust-004',
    customerName: 'Laura Martínez',
    customerEmail: 'laura@example.com',
    notes: 'Cliente no se presentó a recoger',
    createdAt: '2025-06-04T09:00:00Z',
    updatedAt: '2025-06-07T18:00:00Z',
    items: [
      {
        id: 'si-007',
        cardId: 'pkmn-009',
        cardName: 'Mew VMAX',
        cardImageUrl: 'https://images.pokemontcg.io/swsh8/269_hires.png',
        setName: 'Fusion Strike',
        setCode: 'FST',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.MODERATELY_PLAYED,
        quantity: 1,
        unitPrice: 28.0,
      },
    ],
  },
  {
    id: 'sale-006',
    code: 'KSP-P7Q8R9',
    status: SALE_STATUS.NEW,
    tcgType: TCG_TYPES.MAGIC,
    customerId: 'cust-005',
    customerName: 'Diego Torres',
    customerEmail: 'diego@example.com',
    createdAt: '2025-06-10T08:00:00Z',
    updatedAt: '2025-06-10T08:00:00Z',
    items: [
      {
        id: 'si-008',
        cardId: 'mtg-003',
        cardName: 'Sheoldred, the Apocalypse',
        cardImageUrl: 'https://cards.scryfall.io/large/front/d/6/d67be074-cdd4-41d9-ac89-0a0456c4e4b2.jpg',
        setName: 'Dominaria United',
        setCode: 'DMU',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 95.0,
      },
      {
        id: 'si-009',
        cardId: 'mtg-001',
        cardName: 'Lightning Bolt',
        cardImageUrl: 'https://cards.scryfall.io/large/front/9/5/9521375e-0bc1-45ef-b513-6d332a25f9d2.jpg',
        setName: 'Fourth Edition',
        setCode: '4ED',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 4,
        unitPrice: 2.5,
      },
    ],
  },
  {
    id: 'sale-007',
    code: 'KSP-S1T2U3',
    status: SALE_STATUS.IN_PROGRESS,
    tcgType: TCG_TYPES.MAGIC,
    customerId: 'cust-006',
    customerName: 'Fernanda López',
    customerEmail: 'fernanda@example.com',
    notes: 'Pedido urgente para torneo',
    createdAt: '2025-06-09T17:30:00Z',
    updatedAt: '2025-06-10T09:00:00Z',
    items: [
      {
        id: 'si-010',
        cardId: 'mtg-002',
        cardName: 'Ragavan, Nimble Pilferer',
        cardImageUrl: 'https://cards.scryfall.io/large/front/a/9/a9738cda-adb1-47fb-9f4c-ecd930228c4d.jpg',
        setName: 'Modern Horizons 2',
        setCode: 'MH2',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 75.0,
      },
      {
        id: 'si-011',
        cardId: 'mtg-005',
        cardName: 'The One Ring',
        cardImageUrl: 'https://cards.scryfall.io/large/front/d/5/d5806e68-1054-458e-866d-1f2470f682b2.jpg',
        setName: 'Lord of the Rings',
        setCode: 'LTR',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 60.0,
      },
    ],
  },
  {
    id: 'sale-008',
    code: 'KSP-V4W5X6',
    status: SALE_STATUS.READY_FOR_PICKUP,
    tcgType: TCG_TYPES.MAGIC,
    customerId: 'cust-007',
    customerName: 'Miguel Ángel Ruiz',
    customerEmail: 'miguel@example.com',
    createdAt: '2025-06-08T11:00:00Z',
    updatedAt: '2025-06-09T15:45:00Z',
    items: [
      {
        id: 'si-012',
        cardId: 'mtg-007',
        cardName: 'Wrenn and Six',
        cardImageUrl: 'https://cards.scryfall.io/large/front/4/a/4a706ecf-3277-40e3-871c-4ba4ead16e20.jpg',
        setName: 'Modern Horizons',
        setCode: 'MH1',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 1,
        unitPrice: 55.0,
      },
    ],
  },
  {
    id: 'sale-009',
    code: 'KSP-Y7Z8A1',
    status: SALE_STATUS.COMPLETED,
    tcgType: TCG_TYPES.MAGIC,
    customerId: 'cust-005',
    customerName: 'Diego Torres',
    customerEmail: 'diego@example.com',
    createdAt: '2025-06-03T13:00:00Z',
    updatedAt: '2025-06-04T10:30:00Z',
    items: [
      {
        id: 'si-013',
        cardId: 'mtg-012',
        cardName: 'Orcish Bowmasters',
        cardImageUrl: 'https://cards.scryfall.io/large/front/7/c/7c024bae-5631-4e20-ac69-df392ac9e109.jpg',
        setName: 'Lord of the Rings',
        setCode: 'LTR',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        unitPrice: 50.0,
      },
      {
        id: 'si-014',
        cardId: 'mtg-006',
        cardName: 'Fatal Push',
        cardImageUrl: 'https://cards.scryfall.io/large/front/b/5/b5e81649-9954-424c-89d1-f87d73b66047.jpg',
        setName: 'Aether Revolt',
        setCode: 'AER',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        unitPrice: 5.0,
      },
    ],
  },
  {
    id: 'sale-010',
    code: 'KSP-B2C3D4',
    status: SALE_STATUS.CANCELLED,
    tcgType: TCG_TYPES.MAGIC,
    customerId: 'cust-008',
    customerName: 'Patricia Vega',
    customerEmail: 'patricia@example.com',
    notes: 'Cancelado por cliente - fuera de zona de entrega',
    createdAt: '2025-06-02T15:00:00Z',
    updatedAt: '2025-06-03T08:00:00Z',
    items: [
      {
        id: 'si-015',
        cardId: 'mtg-017',
        cardName: 'Chalice of the Void',
        cardImageUrl: 'https://cards.scryfall.io/large/front/1/f/1f0d2e8e-c8f2-4b31-a6ba-6283fc8740d4.jpg',
        setName: 'Masters 25',
        setCode: 'A25',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        unitPrice: 65.0,
      },
    ],
  },
];
