import { IInventoryItem } from '../../domain/types';
import { STOCK_STATUSES } from '../../domain/constants';
import { CARD_CONDITIONS } from '@/lib/types/card.types';
import { TCG_TYPES } from '@/lib/types/tcg.types';

export const MOCK_INVENTORY_ITEMS: IInventoryItem[] = [
  {
    id: 'inv-001',
    cardId: 'pkmn-001',
    name: 'Charizard ex',
    setName: 'Obsidian Flames',
    setCode: 'OBF',
    number: '125',
    rarity: 'Special Art Rare',
    imageUrl: 'https://images.pokemontcg.io/sv3/125_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    condition: CARD_CONDITIONS.NEAR_MINT,
    stock: 3,
    stockStatus: STOCK_STATUSES.AVAILABLE,
    buyPrice: 45.0,
    sellPrice: 65.0,
    lastSoldAt: '2026-01-15T10:30:00Z',
    avgDaysInInventory: 12.5,
  },
  {
    id: 'inv-002',
    cardId: 'pkmn-001',
    name: 'Charizard ex',
    setName: 'Obsidian Flames',
    setCode: 'OBF',
    number: '125',
    rarity: 'Special Art Rare',
    imageUrl: 'https://images.pokemontcg.io/sv3/125_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
    stock: 1,
    stockStatus: STOCK_STATUSES.AVAILABLE,
    buyPrice: 35.0,
    sellPrice: 50.0,
    lastSoldAt: '2026-01-20T14:00:00Z',
    avgDaysInInventory: 8.0,
  },
  {
    id: 'inv-003',
    cardId: 'pkmn-002',
    name: 'Pikachu VMAX',
    setName: 'Vivid Voltage',
    setCode: 'VIV',
    number: '044',
    rarity: 'Ultra Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh4/44_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    condition: CARD_CONDITIONS.NEAR_MINT,
    stock: 5,
    stockStatus: STOCK_STATUSES.AVAILABLE,
    buyPrice: 20.0,
    sellPrice: 30.0,
    lastSoldAt: '2026-02-01T09:00:00Z',
    avgDaysInInventory: 5.3,
  },
  {
    id: 'inv-004',
    cardId: 'pkmn-003',
    name: 'Mewtwo VSTAR',
    setName: 'Pokémon GO',
    setCode: 'PGO',
    number: '031',
    rarity: 'Ultra Rare',
    imageUrl: 'https://images.pokemontcg.io/pgo/31_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    condition: CARD_CONDITIONS.NEAR_MINT,
    stock: 0,
    stockStatus: STOCK_STATUSES.UNAVAILABLE,
    buyPrice: 15.0,
    sellPrice: 22.0,
    lastSoldAt: '2025-12-10T16:45:00Z',
    avgDaysInInventory: 20.0,
  },
  {
    id: 'inv-005',
    cardId: 'pkmn-004',
    name: 'Umbreon VMAX',
    setName: 'Evolving Skies',
    setCode: 'EVS',
    number: '095',
    rarity: 'Secret Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh7/95_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    condition: CARD_CONDITIONS.MODERATELY_PLAYED,
    stock: 2,
    stockStatus: STOCK_STATUSES.AWAITING_PICKUP,
    buyPrice: 80.0,
    sellPrice: 120.0,
    lastSoldAt: null,
    avgDaysInInventory: null,
  },
  {
    id: 'inv-006',
    cardId: 'mtg-001',
    name: 'Ragavan, Nimble Pilferer',
    setName: 'Modern Horizons 2',
    setCode: 'MH2',
    number: '138',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    condition: CARD_CONDITIONS.NEAR_MINT,
    stock: 4,
    stockStatus: STOCK_STATUSES.AVAILABLE,
    buyPrice: 55.0,
    sellPrice: 75.0,
    lastSoldAt: '2026-01-28T11:00:00Z',
    avgDaysInInventory: 7.2,
  },
  {
    id: 'inv-007',
    cardId: 'mtg-002',
    name: 'The One Ring',
    setName: 'Lord of the Rings',
    setCode: 'LTR',
    number: '246',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    condition: CARD_CONDITIONS.NEAR_MINT,
    stock: 1,
    stockStatus: STOCK_STATUSES.AWAITING_PICKUP,
    buyPrice: 40.0,
    sellPrice: 60.0,
    lastSoldAt: '2026-02-05T13:30:00Z',
    avgDaysInInventory: 3.0,
  },
  {
    id: 'inv-008',
    cardId: 'mtg-003',
    name: 'Sheoldred, the Apocalypse',
    setName: 'Dominaria United',
    setCode: 'DMU',
    number: '107',
    rarity: 'Mythic Rare',
    imageUrl: '',
    tcgType: TCG_TYPES.MAGIC,
    condition: CARD_CONDITIONS.HEAVILY_PLAYED,
    stock: 0,
    stockStatus: STOCK_STATUSES.UNAVAILABLE,
    buyPrice: 30.0,
    sellPrice: 45.0,
    lastSoldAt: '2025-11-20T08:00:00Z',
    avgDaysInInventory: 35.0,
  },
];
