import { IInventoryMovement } from '../../domain/types';
import { MOVEMENT_TYPES } from '../../domain/constants';
import { TCG_TYPES } from '@/lib/types/tcg.types';

export const MOCK_MOVEMENTS: IInventoryMovement[] = [
  {
    id: 'mov-001',
    inventoryItemId: 'inv-001',
    cardName: 'Charizard ex',
    cardImageUrl: 'https://images.pokemontcg.io/sv3/125_hires.png',
    setName: 'Obsidian Flames',
    setCode: 'OBF',
    cardNumber: '125',
    tcgType: TCG_TYPES.POKEMON,
    type: MOVEMENT_TYPES.PURCHASE_ENTRY,
    quantity: 3,
    reason: 'Compra a vendedor local',
    userName: 'Carlos Admin',
    reference: 'PUR-2026-001',
    createdAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'mov-002',
    inventoryItemId: 'inv-001',
    cardName: 'Charizard ex',
    cardImageUrl: 'https://images.pokemontcg.io/sv3/125_hires.png',
    setName: 'Obsidian Flames',
    setCode: 'OBF',
    cardNumber: '125',
    tcgType: TCG_TYPES.POKEMON,
    type: MOVEMENT_TYPES.SALE_EXIT,
    quantity: 1,
    reason: 'Venta en mostrador',
    userName: 'Ana Recepción',
    reference: 'SAL-2026-015',
    createdAt: '2026-01-15T10:30:00Z',
  },
  {
    id: 'mov-003',
    inventoryItemId: 'inv-003',
    cardName: 'Pikachu VMAX',
    cardImageUrl: 'https://images.pokemontcg.io/swsh4/44_hires.png',
    setName: 'Vivid Voltage',
    setCode: 'VIV',
    cardNumber: '044',
    tcgType: TCG_TYPES.POKEMON,
    type: MOVEMENT_TYPES.PURCHASE_ENTRY,
    quantity: 5,
    reason: 'Compra lote mixto',
    userName: 'Carlos Admin',
    reference: 'PUR-2026-003',
    createdAt: '2026-01-20T14:00:00Z',
  },
  {
    id: 'mov-004',
    inventoryItemId: 'inv-003',
    cardName: 'Pikachu VMAX',
    cardImageUrl: 'https://images.pokemontcg.io/swsh4/44_hires.png',
    setName: 'Vivid Voltage',
    setCode: 'VIV',
    cardNumber: '044',
    tcgType: TCG_TYPES.POKEMON,
    type: MOVEMENT_TYPES.SALE_EXIT,
    quantity: 2,
    reason: 'Pedido carpeta digital',
    userName: 'Ana Recepción',
    reference: 'SAL-2026-022',
    createdAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'mov-005',
    inventoryItemId: 'inv-005',
    cardName: 'Umbreon VMAX',
    cardImageUrl: 'https://images.pokemontcg.io/swsh7/95_hires.png',
    setName: 'Evolving Skies',
    setCode: 'EVS',
    cardNumber: '095',
    tcgType: TCG_TYPES.POKEMON,
    type: MOVEMENT_TYPES.MANUAL_ADJUSTMENT,
    quantity: -1,
    reason: 'Corrección de inventario físico',
    userName: 'Carlos Admin',
    reference: null,
    createdAt: '2026-01-25T16:00:00Z',
  },
  {
    id: 'mov-006',
    inventoryItemId: 'inv-006',
    cardName: 'Ragavan, Nimble Pilferer',
    cardImageUrl: '',
    setName: 'Modern Horizons 2',
    setCode: 'MH2',
    cardNumber: '138',
    tcgType: TCG_TYPES.MAGIC,
    type: MOVEMENT_TYPES.PURCHASE_ENTRY,
    quantity: 4,
    reason: 'Compra colección completa',
    userName: 'Carlos Admin',
    reference: 'PUR-2026-005',
    createdAt: '2026-01-18T11:00:00Z',
  },
  {
    id: 'mov-007',
    inventoryItemId: 'inv-007',
    cardName: 'The One Ring',
    cardImageUrl: '',
    setName: 'Lord of the Rings',
    setCode: 'LTR',
    cardNumber: '246',
    tcgType: TCG_TYPES.MAGIC,
    type: MOVEMENT_TYPES.SALE_EXIT,
    quantity: 1,
    reason: 'Venta en mostrador',
    userName: 'Ana Recepción',
    reference: 'SAL-2026-030',
    createdAt: '2026-02-05T13:30:00Z',
  },
  {
    id: 'mov-008',
    inventoryItemId: 'inv-008',
    cardName: 'Sheoldred, the Apocalypse',
    cardImageUrl: '',
    setName: 'Dominaria United',
    setCode: 'DMU',
    cardNumber: '107',
    tcgType: TCG_TYPES.MAGIC,
    type: MOVEMENT_TYPES.MANUAL_ADJUSTMENT,
    quantity: 2,
    reason: 'Reconteo de inventario',
    userName: 'Carlos Admin',
    reference: null,
    createdAt: '2026-02-07T10:00:00Z',
  },
  {
    id: 'mov-009',
    inventoryItemId: 'inv-002',
    cardName: 'Charizard ex',
    cardImageUrl: 'https://images.pokemontcg.io/sv3/125_hires.png',
    setName: 'Obsidian Flames',
    setCode: 'OBF',
    cardNumber: '125',
    tcgType: TCG_TYPES.POKEMON,
    type: MOVEMENT_TYPES.PURCHASE_ENTRY,
    quantity: 1,
    reason: 'Compra individual',
    userName: 'Carlos Admin',
    reference: 'PUR-2026-008',
    createdAt: '2026-01-22T08:30:00Z',
  },
  {
    id: 'mov-010',
    inventoryItemId: 'inv-004',
    cardName: 'Mewtwo VSTAR',
    cardImageUrl: 'https://images.pokemontcg.io/pgo/31_hires.png',
    setName: 'Pokémon GO',
    setCode: 'PGO',
    cardNumber: '031',
    tcgType: TCG_TYPES.POKEMON,
    type: MOVEMENT_TYPES.SALE_EXIT,
    quantity: 2,
    reason: 'Pedido carpeta digital',
    userName: 'Ana Recepción',
    reference: 'SAL-2026-012',
    createdAt: '2025-12-10T16:45:00Z',
  },
  {
    id: 'mov-011',
    inventoryItemId: 'inv-006',
    cardName: 'Ragavan, Nimble Pilferer',
    cardImageUrl: '',
    setName: 'Modern Horizons 2',
    setCode: 'MH2',
    cardNumber: '138',
    tcgType: TCG_TYPES.MAGIC,
    type: MOVEMENT_TYPES.SALE_EXIT,
    quantity: 1,
    reason: 'Venta en mostrador',
    userName: 'Ana Recepción',
    reference: 'SAL-2026-035',
    createdAt: '2026-01-28T11:00:00Z',
  },
  {
    id: 'mov-012',
    inventoryItemId: 'inv-005',
    cardName: 'Umbreon VMAX',
    cardImageUrl: 'https://images.pokemontcg.io/swsh7/95_hires.png',
    setName: 'Evolving Skies',
    setCode: 'EVS',
    cardNumber: '095',
    tcgType: TCG_TYPES.POKEMON,
    type: MOVEMENT_TYPES.PURCHASE_ENTRY,
    quantity: 3,
    reason: 'Compra a vendedor recurrente',
    userName: 'Carlos Admin',
    reference: 'PUR-2026-010',
    createdAt: '2026-02-03T09:15:00Z',
  },
];
