import { ICardSearchResult } from '../../domain/types';
import { TCG_TYPES } from '@/lib/types/tcg.types';

export const MOCK_CARD_SEARCH_RESULTS: ICardSearchResult[] = [
  {
    guid: 'pkmn-001',
    name: 'Charizard ex',
    setName: 'Obsidian Flames',
    setCode: 'OBF',
    number: '125',
    rarity: 'Special Art Rare',
    imageUrl: 'https://images.pokemontcg.io/sv3/125_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    metrics: {
      referencePrice: 65.0,
      currentStock: 3,
      lastSaleDate: '2026-01-28',
      daysInInventory: 12,
      wishlistCount: 8,
    },
  },
  {
    guid: 'pkmn-002',
    name: 'Pikachu VMAX',
    setName: 'Vivid Voltage',
    setCode: 'VIV',
    number: '044',
    rarity: 'Ultra Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh4/44_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    metrics: {
      referencePrice: 30.0,
      currentStock: 5,
      lastSaleDate: '2026-02-05',
      daysInInventory: 4,
      wishlistCount: 3,
    },
  },
  {
    guid: 'pkmn-003',
    name: 'Mewtwo V',
    setName: 'Pokémon GO',
    setCode: 'PGO',
    number: '030',
    rarity: 'Rare Holo V',
    imageUrl: 'https://images.pokemontcg.io/pgo/30_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    metrics: {
      referencePrice: 12.0,
      currentStock: 2,
      lastSaleDate: '2026-01-15',
      daysInInventory: 25,
      wishlistCount: 1,
    },
  },
  {
    guid: 'pkmn-004',
    name: 'Umbreon VMAX',
    setName: 'Evolving Skies',
    setCode: 'EVS',
    number: '095',
    rarity: 'Ultra Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh7/95_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    metrics: {
      referencePrice: 220.0,
      currentStock: 1,
      lastSaleDate: '2026-02-01',
      daysInInventory: 8,
      wishlistCount: 15,
    },
  },
  {
    guid: 'pkmn-005',
    name: 'Gardevoir ex',
    setName: 'Scarlet & Violet',
    setCode: 'SVI',
    number: '086',
    rarity: 'Double Rare',
    imageUrl: 'https://images.pokemontcg.io/sv1/86_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    metrics: {
      referencePrice: 8.0,
      currentStock: 7,
      lastSaleDate: '2026-02-07',
      daysInInventory: 2,
      wishlistCount: 0,
    },
  },
  {
    guid: 'pkmn-006',
    name: 'Rayquaza VMAX',
    setName: 'Evolving Skies',
    setCode: 'EVS',
    number: '218',
    rarity: 'Secret Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh7/218_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    metrics: {
      referencePrice: 120.0,
      currentStock: 0,
      lastSaleDate: null,
      daysInInventory: 0,
      wishlistCount: 12,
    },
  },
  {
    guid: 'pkmn-007',
    name: 'Mew VMAX',
    setName: 'Fusion Strike',
    setCode: 'FST',
    number: '269',
    rarity: 'Secret Rare',
    imageUrl: 'https://images.pokemontcg.io/swsh8/269_hires.png',
    tcgType: TCG_TYPES.POKEMON,
    metrics: {
      referencePrice: 28.0,
      currentStock: 4,
      lastSaleDate: '2026-01-20',
      daysInInventory: 20,
      wishlistCount: 5,
    },
  },
  {
    guid: 'mtg-001',
    name: 'Sheoldred, the Apocalypse',
    setName: 'Dominaria United',
    setCode: 'DMU',
    number: '107',
    rarity: 'Mythic Rare',
    imageUrl: 'https://cards.scryfall.io/large/front/d/6/d67be074-cdd4-41d9-ac89-0a0456c4e4b2.jpg',
    tcgType: TCG_TYPES.MAGIC,
    metrics: {
      referencePrice: 850.0,
      currentStock: 1,
      lastSaleDate: '2026-02-03',
      daysInInventory: 6,
      wishlistCount: 20,
    },
  },
  {
    guid: 'mtg-002',
    name: 'The One Ring',
    setName: 'Lord of the Rings',
    setCode: 'LTR',
    number: '246',
    rarity: 'Mythic Rare',
    imageUrl: 'https://cards.scryfall.io/large/front/d/5/d5806e68-1054-458e-866d-1f2470f682b2.jpg',
    tcgType: TCG_TYPES.MAGIC,
    metrics: {
      referencePrice: 1200.0,
      currentStock: 0,
      lastSaleDate: null,
      daysInInventory: 0,
      wishlistCount: 25,
    },
  },
  {
    guid: 'mtg-003',
    name: 'Ragavan, Nimble Pilferer',
    setName: 'Modern Horizons 2',
    setCode: 'MH2',
    number: '138',
    rarity: 'Mythic Rare',
    imageUrl: 'https://cards.scryfall.io/large/front/a/9/a9738cda-adb1-47fb-9f4c-ecd930228c4d.jpg',
    tcgType: TCG_TYPES.MAGIC,
    metrics: {
      referencePrice: 950.0,
      currentStock: 2,
      lastSaleDate: '2026-01-30',
      daysInInventory: 10,
      wishlistCount: 9,
    },
  },
];
