import { IPurchase, PURCHASE_STATUS, PAYMENT_METHOD } from '../../domain/types';
import { TCG_TYPES } from '@/lib/types/tcg.types';
import { CARD_CONDITIONS } from '@/lib/types/card.types';

export const MOCK_PURCHASES: IPurchase[] = [
  {
    guid: 'pur-001',
    code: 'CMP-2026-001',
    status: PURCHASE_STATUS.FINALIZED,
    seller: {
      guid: 'seller-001',
      name: 'Carlos Mendoza',
      phone: '+52 55 1234 5678',
      email: 'carlos.mendoza@email.com',
    },
    items: [
      {
        guid: 'pi-001',
        cardGuid: 'pkmn-001',
        cardName: 'Charizard ex',
        cardImageUrl: 'https://images.pokemontcg.io/sv3/125_hires.png',
        setName: 'Obsidian Flames',
        setCode: 'OBF',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 2,
        offerPrice: 45.0,
        sellPrice: 65.0,
      },
      {
        guid: 'pi-002',
        cardGuid: 'pkmn-004',
        cardName: 'Umbreon VMAX',
        cardImageUrl: 'https://images.pokemontcg.io/swsh7/95_hires.png',
        setName: 'Evolving Skies',
        setCode: 'EVS',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 1,
        offerPrice: 150.0,
        sellPrice: 220.0,
      },
    ],
    payments: [
      { method: PAYMENT_METHOD.CASH, amount: 240.0 },
    ],
    tcgType: TCG_TYPES.POKEMON,
    buyer: { guid: 'buyer-001', name: 'Buyer 1' },
    createdDate: '2026-02-01T10:30:00Z',
    updatedDate: '2026-02-01T14:00:00Z',
  },
  {
    guid: 'pur-002',
    code: 'CMP-2026-002',
    status: PURCHASE_STATUS.QUOTED,
    seller: {
      guid: 'seller-002',
      name: 'Ana García',
      phone: '+52 33 9876 5432',
      email: 'ana.garcia@email.com',
    },
    items: [
      {
        guid: 'pi-003',
        cardGuid: 'pkmn-005',
        cardName: 'Gardevoir ex',
        cardImageUrl: 'https://images.pokemontcg.io/sv1/86_hires.png',
        setName: 'Scarlet & Violet',
        setCode: 'SVI',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 4,
        offerPrice: 5.0,
        sellPrice: 8.0,
      },
    ],
    payments: [],
    tcgType: TCG_TYPES.POKEMON,
    buyer: { guid: 'buyer-002', name: 'Buyer 2' },
    notes: 'Vendedora quiere respuesta antes del viernes',
    createdDate: '2026-02-03T09:15:00Z',
    updatedDate: '2026-02-03T09:15:00Z',
  },
  {
    guid: 'pur-003',
    code: 'CMP-2026-003',
    status: PURCHASE_STATUS.DRAFT,
    seller: {
      guid: 'seller-003',
      name: 'Roberto López',
      phone: '+52 81 5555 1234',
    },
    items: [
      {
        guid: 'pi-004',
        cardGuid: 'mtg-001',
        cardName: 'Sheoldred, the Apocalypse',
        cardImageUrl: 'https://cards.scryfall.io/large/front/d/6/d67be074-cdd4-41d9-ac89-0a0456c4e4b2.jpg',
        setName: 'Dominaria United',
        setCode: 'DMU',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        offerPrice: 550.0,
        sellPrice: 850.0,
      },
      {
        guid: 'pi-005',
        cardGuid: 'mtg-003',
        cardName: 'Ragavan, Nimble Pilferer',
        cardImageUrl: 'https://cards.scryfall.io/large/front/a/9/a9738cda-adb1-47fb-9f4c-ecd930228c4d.jpg',
        setName: 'Modern Horizons 2',
        setCode: 'MH2',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 2,
        offerPrice: 600.0,
        sellPrice: 950.0,
      },
    ],
    payments: [],
    tcgType: TCG_TYPES.MAGIC,
    buyer: { guid: 'buyer-001', name: 'Buyer 1' },
    notes: 'Lote de cartas Modern',
    createdDate: '2026-02-05T16:45:00Z',
    updatedDate: '2026-02-05T16:45:00Z',
  },
  {
    guid: 'pur-004',
    code: 'CMP-2026-004',
    status: PURCHASE_STATUS.WAITING_PRICE,
    seller: {
      guid: 'seller-004',
      name: 'María Fernández',
      phone: '+52 55 4321 8765',
      email: 'maria.fernandez@email.com',
    },
    items: [
      {
        guid: 'pi-006',
        cardGuid: 'pkmn-002',
        cardName: 'Pikachu VMAX',
        cardImageUrl: 'https://images.pokemontcg.io/swsh4/44_hires.png',
        setName: 'Vivid Voltage',
        setCode: 'VIV',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 3,
        offerPrice: 18.0,
        sellPrice: 30.0,
      },
    ],
    payments: [],
    tcgType: TCG_TYPES.POKEMON,
    buyer: { guid: 'buyer-002', name: 'Buyer 2' },
    createdDate: '2026-02-06T11:00:00Z',
    updatedDate: '2026-02-07T09:30:00Z',
  },
  {
    guid: 'pur-005',
    code: 'CMP-2026-005',
    status: PURCHASE_STATUS.REJECTED,
    seller: {
      guid: 'seller-005',
      name: 'Diego Ramírez',
      phone: '+52 33 1111 2222',
    },
    items: [
      {
        guid: 'pi-007',
        cardGuid: 'pkmn-007',
        cardName: 'Mew VMAX',
        cardImageUrl: 'https://images.pokemontcg.io/swsh8/269_hires.png',
        setName: 'Fusion Strike',
        setCode: 'FST',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.HEAVILY_PLAYED,
        quantity: 2,
        offerPrice: 12.0,
        sellPrice: 28.0,
      },
    ],
    payments: [],
    tcgType: TCG_TYPES.POKEMON,
    buyer: { guid: 'buyer-001', name: 'Buyer 1' },
    notes: 'Precio no competitivo',
    createdDate: '2026-01-28T14:20:00Z',
    updatedDate: '2026-01-29T10:00:00Z',
  },
  {
    guid: 'pur-006',
    code: 'CMP-2026-006',
    status: PURCHASE_STATUS.FINALIZED,
    seller: {
      guid: 'seller-006',
      name: 'Laura Sánchez',
      phone: '+52 81 3333 4444',
      email: 'laura.sanchez@email.com',
    },
    items: [
      {
        guid: 'pi-008',
        cardGuid: 'pkmn-003',
        cardName: 'Mewtwo V',
        cardImageUrl: 'https://images.pokemontcg.io/pgo/30_hires.png',
        setName: 'Pokémon GO',
        setCode: 'PGO',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.MODERATELY_PLAYED,
        quantity: 5,
        offerPrice: 6.0,
        sellPrice: 12.0,
      },
      {
        guid: 'pi-009',
        cardGuid: 'pkmn-006',
        cardName: 'Rayquaza VMAX',
        cardImageUrl: 'https://images.pokemontcg.io/swsh7/218_hires.png',
        setName: 'Evolving Skies',
        setCode: 'EVS',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        offerPrice: 80.0,
        sellPrice: 120.0,
      },
    ],
    payments: [
      { method: PAYMENT_METHOD.TRANSFER, amount: 80.0 },
      { method: PAYMENT_METHOD.STORE_CREDIT, amount: 30.0 },
    ],
    tcgType: TCG_TYPES.POKEMON,
    buyer: { guid: 'buyer-001', name: 'Buyer 1' },
    createdDate: '2026-01-25T08:00:00Z',
    updatedDate: '2026-01-25T12:30:00Z',
  },
  {
    guid: 'pur-007',
    code: 'CMP-2026-007',
    status: PURCHASE_STATUS.QUOTED,
    seller: {
      guid: 'seller-007',
      name: 'Fernando Torres',
      phone: '+52 55 7777 8888',
      email: 'fernando.t@email.com',
    },
    items: [
      {
        guid: 'pi-010',
        cardGuid: 'mtg-002',
        cardName: 'The One Ring',
        cardImageUrl: 'https://cards.scryfall.io/large/front/d/5/d5806e68-1054-458e-bcd0-27571f2f8571.jpg',
        setName: 'Lord of the Rings',
        setCode: 'LTR',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        offerPrice: 800.0,
        sellPrice: 1200.0,
      },
    ],
    payments: [],
    tcgType: TCG_TYPES.MAGIC,
    buyer: { guid: 'buyer-002', name: 'Buyer 2' },
    createdDate: '2026-02-07T15:00:00Z',
    updatedDate: '2026-02-07T15:00:00Z',
  },
  {
    guid: 'pur-008',
    code: 'CMP-2026-008',
    status: PURCHASE_STATUS.DRAFT,
    seller: {
      guid: 'seller-008',
      name: 'Patricia Ruiz',
      phone: '+52 33 5555 6666',
    },
    items: [
      {
        guid: 'pi-011',
        cardGuid: 'pkmn-001',
        cardName: 'Charizard ex',
        cardImageUrl: 'https://images.pokemontcg.io/sv3/125_hires.png',
        setName: 'Obsidian Flames',
        setCode: 'OBF',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
        quantity: 1,
        offerPrice: 40.0,
        sellPrice: 65.0,
      },
    ],
    payments: [],
    tcgType: TCG_TYPES.POKEMON,
    buyer: { guid: 'buyer-001', name: 'Buyer 1' },
    createdDate: '2026-02-08T10:00:00Z',
    updatedDate: '2026-02-08T10:00:00Z',
  },
  {
    guid: 'pur-009',
    code: 'CMP-2026-009',
    status: PURCHASE_STATUS.FINALIZED,
    seller: {
      guid: 'seller-001',
      name: 'Carlos Mendoza',
      phone: '+52 55 1234 5678',
      email: 'carlos.mendoza@email.com',
    },
    items: [
      {
        guid: 'pi-012',
        cardGuid: 'pkmn-004',
        cardName: 'Umbreon VMAX',
        cardImageUrl: 'https://images.pokemontcg.io/swsh7/95_hires.png',
        setName: 'Evolving Skies',
        setCode: 'EVS',
        tcgType: TCG_TYPES.POKEMON,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        offerPrice: 160.0,
        sellPrice: 220.0,
      },
    ],
    payments: [
      { method: PAYMENT_METHOD.CASH, amount: 160.0 },
    ],
    tcgType: TCG_TYPES.POKEMON,
    buyer: { guid: 'buyer-002', name: 'Buyer 2' },
    createdDate: '2026-01-20T13:00:00Z',
    updatedDate: '2026-01-20T16:00:00Z',
  },
  {
    guid: 'pur-010',
    code: 'CMP-2026-010',
    status: PURCHASE_STATUS.FINALIZED,
    seller: {
      guid: 'seller-003',
      name: 'Roberto López',
      phone: '+52 81 5555 1234',
    },
    items: [
      {
        guid: 'pi-013',
        cardGuid: 'mtg-003',
        cardName: 'Ragavan, Nimble Pilferer',
        cardImageUrl: 'https://cards.scryfall.io/large/front/a/9/a9738cda-adb1-47fb-9f4c-ecd930228c4d.jpg',
        setName: 'Modern Horizons 2',
        setCode: 'MH2',
        tcgType: TCG_TYPES.MAGIC,
        condition: CARD_CONDITIONS.NEAR_MINT,
        quantity: 1,
        offerPrice: 650.0,
        sellPrice: 950.0,
      },
    ],
    payments: [
      { method: PAYMENT_METHOD.TRANSFER, amount: 650.0 },
    ],
    tcgType: TCG_TYPES.MAGIC,
    buyer: { guid: 'buyer-001', name: 'Buyer 1' },
    createdDate: '2026-01-15T09:00:00Z',
    updatedDate: '2026-01-15T11:30:00Z',
  },
];
