import { IPurchaseItem } from '../../domain/types';
import { CARD_CONDITIONS } from '../../domain/constants';
import { TCG_TYPES } from '@/lib/types/tcg.types';

export const MOCK_PURCHASE_ITEMS: IPurchaseItem[] = [
  {
    id: 'pi-001',
    cardId: 'pkmn-001',
    cardName: 'Charizard ex',
    cardImageUrl: 'https://images.pokemontcg.io/sv3/125_hires.png',
    setName: 'Obsidian Flames',
    setCode: 'OBF',
    tcgType: TCG_TYPES.POKEMON,
    condition: CARD_CONDITIONS.NEAR_MINT,
    quantity: 2,
    unitBuyPrice: 45.0,
    unitSellPrice: 65.0,
  },
  {
    id: 'pi-002',
    cardId: 'pkmn-004',
    cardName: 'Umbreon VMAX',
    cardImageUrl: 'https://images.pokemontcg.io/swsh7/95_hires.png',
    setName: 'Evolving Skies',
    setCode: 'EVS',
    tcgType: TCG_TYPES.POKEMON,
    condition: CARD_CONDITIONS.LIGHTLY_PLAYED,
    quantity: 1,
    unitBuyPrice: 150.0,
    unitSellPrice: 220.0,
  },
  {
    id: 'pi-003',
    cardId: 'pkmn-005',
    cardName: 'Gardevoir ex',
    cardImageUrl: 'https://images.pokemontcg.io/sv1/86_hires.png',
    setName: 'Scarlet & Violet',
    setCode: 'SVI',
    tcgType: TCG_TYPES.POKEMON,
    condition: CARD_CONDITIONS.MODERATELY_PLAYED,
    quantity: 3,
    unitBuyPrice: 4.0,
    unitSellPrice: 8.0,
  },
  {
    id: 'pi-004',
    cardId: 'pkmn-008',
    cardName: 'Rayquaza VMAX',
    cardImageUrl: 'https://images.pokemontcg.io/swsh7/218_hires.png',
    setName: 'Evolving Skies',
    setCode: 'EVS',
    tcgType: TCG_TYPES.POKEMON,
    condition: CARD_CONDITIONS.NEAR_MINT,
    quantity: 1,
    unitBuyPrice: 85.0,
    unitSellPrice: 120.0,
  },
  {
    id: 'pi-005',
    cardId: 'pkmn-009',
    cardName: 'Mew VMAX',
    cardImageUrl: 'https://images.pokemontcg.io/swsh8/269_hires.png',
    setName: 'Fusion Strike',
    setCode: 'FST',
    tcgType: TCG_TYPES.POKEMON,
    condition: CARD_CONDITIONS.HEAVILY_PLAYED,
    quantity: 2,
    unitBuyPrice: 18.0,
    unitSellPrice: 28.0,
  },
];
